#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color "#547fbf"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart Apps

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
bspc config focus_follows_pointer true
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1


   
     xsetroot -cursor_name left_ptr
